stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# This job will run automatically on every push
ecomm-tests:
  stage: test
  image: maven:3.8-openjdk-17
  script:
    - mvn clean test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - reports/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"